 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: App
    environment: dev
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: App
      environment: dev
  # below is the pod definition
  template:
    metadata:
      labels:
         component: frontend
         project: expense
         tier: App
         environment: dev
    spec:
      containers:
      - name: frontend
        image: swaroop02/frontend:1.0
        

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: App
    environment: dev  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---



   
        
          