apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: web
    environment: dev
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: web
      environment: dev
  # below is the pod definition
  template:
    metadata:
      labels:
         component: backend
         project: expense
         tier: web
         environment: dev
    spec:
      containers:
      - name: backend
        image: swaroop02/backend:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: web
    environment: dev  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
        
          